"""add iy_article slug

Revision ID: 37b32fa5627f
Revises: 
Create Date: 2019-07-14 10:29:50.071210

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '37b32fa5627f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('iy_article', sa.Column('slug', sa.String(length=128), nullable=True, comment='文章索引字符'))
    op.create_unique_constraint(None, 'iy_article', ['slug'])
    op.create_unique_constraint(None, 'iy_category', ['category_name'])
    op.add_column('iy_comment', sa.Column('commented_post_id', sa.Integer(), nullable=True, comment='评论文章id'))
    op.add_column('iy_comment', sa.Column('create_timestamp', sa.DateTime(), nullable=True, comment='评论时间'))
    op.add_column('iy_comment', sa.Column('replied_id', sa.Integer(), nullable=True, comment='回复id'))
    op.alter_column('iy_comment', 'author',
                    existing_type=mysql.VARCHAR(length=30),
                    comment='评论者名称',
                    existing_nullable=True)
    op.alter_column('iy_comment', 'body',
                    existing_type=mysql.TEXT(),
                    comment='评论内容',
                    existing_nullable=True)
    op.alter_column('iy_comment', 'email',
                    existing_type=mysql.VARCHAR(length=254),
                    comment='评论者邮箱',
                    existing_nullable=True)
    op.alter_column('iy_comment', 'from_admin',
                    existing_type=mysql.TINYINT(display_width=1),
                    comment='来自作者',
                    existing_nullable=True)
    op.alter_column('iy_comment', 'reviewed',
                    existing_type=mysql.TINYINT(display_width=1),
                    comment='评论审核',
                    existing_nullable=True)
    op.alter_column('iy_comment', 'site',
                    existing_type=mysql.VARCHAR(length=255),
                    comment='评论者网址',
                    existing_nullable=True)
    op.create_index(op.f('ix_iy_comment_create_timestamp'), 'iy_comment', ['create_timestamp'], unique=False)
    op.drop_index('ix_iy_comment_timestamp', table_name='iy_comment')
    op.create_foreign_key(None, 'iy_comment', 'iy_article', ['commented_post_id'], ['post_id'])
    op.create_foreign_key(None, 'iy_comment', 'iy_comment', ['replied_id'], ['id'])
    op.drop_column('iy_comment', 'timestamp')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('iy_comment', sa.Column('timestamp', mysql.DATETIME(), nullable=True))
    op.drop_constraint(None, 'iy_comment', type_='foreignkey')
    op.drop_constraint(None, 'iy_comment', type_='foreignkey')
    op.create_index('ix_iy_comment_timestamp', 'iy_comment', ['timestamp'], unique=False)
    op.drop_index(op.f('ix_iy_comment_create_timestamp'), table_name='iy_comment')
    op.alter_column('iy_comment', 'site',
                    existing_type=mysql.VARCHAR(length=255),
                    comment=None,
                    existing_comment='评论者网址',
                    existing_nullable=True)
    op.alter_column('iy_comment', 'reviewed',
                    existing_type=mysql.TINYINT(display_width=1),
                    comment=None,
                    existing_comment='评论审核',
                    existing_nullable=True)
    op.alter_column('iy_comment', 'from_admin',
                    existing_type=mysql.TINYINT(display_width=1),
                    comment=None,
                    existing_comment='来自作者',
                    existing_nullable=True)
    op.alter_column('iy_comment', 'email',
                    existing_type=mysql.VARCHAR(length=254),
                    comment=None,
                    existing_comment='评论者邮箱',
                    existing_nullable=True)
    op.alter_column('iy_comment', 'body',
                    existing_type=mysql.TEXT(),
                    comment=None,
                    existing_comment='评论内容',
                    existing_nullable=True)
    op.alter_column('iy_comment', 'author',
                    existing_type=mysql.VARCHAR(length=30),
                    comment=None,
                    existing_comment='评论者名称',
                    existing_nullable=True)
    op.drop_column('iy_comment', 'replied_id')
    op.drop_column('iy_comment', 'create_timestamp')
    op.drop_column('iy_comment', 'commented_post_id')
    op.drop_constraint(None, 'iy_category', type_='unique')
    op.drop_constraint(None, 'iy_article', type_='unique')
    op.drop_column('iy_article', 'slug')
    # ### end Alembic commands ###
